### ISSUE TITLE
subito[dot]it web page source code changed. 

### ISSUE THREAD

**Issue by margiodo** [morrolinux/subito-it-searcher#1]
Hi morro,

i checked-out your source code. In one month the subito[dot]it developers  have changed the site source code. I think they now use CSS to create dynamic web page (i am not a web developer, so sorry if i'm writing rubbish).

However, i modify your source code to model with the new web page structure using regular expression, if you are interested, contact me.

Best regard,
margiodo

**Comment by morrolinux** [comment]
Yeah go ahead, you can create a pull request and I'll merge it. (If it looks alright)
