### ISSUE TITLE
TypeError: can only concatenate str (not "Tag") to str

### ISSUE THREAD

**Issue by gstru** [morrolinux/subito-it-searcher#13]
When the price doesn't exist the script should save the price as unknown in the json file. 
Instead it scrapes the span tag and prints concatenation error.

![image](https://user-images.githubusercontent.com/58074638/134774358-610aba6a-57cc-4d6b-b0ef-fcdc07f41eae.png)

A quick solution could be to check the variable.

```
from bs4 import BeautifulSoup, Tag


price_soup = BeautifulSoup(price, 'html.parser')
if type(price_soup == Tag)
```

**Comment by morrolinux** [comment]
Hi,
This project is no longer maintained but you can of course make a PR with your tested solution ad I'll just merge it :)
Thank you
