### ISSUE TITLE
aiuto

### ISSUE THREAD

**Issue by eliafirenze** [morrolinux/subito-it-searcher#15]
non ho capito ma il comando: pyhton3 subito-searcher.py --addtoken [YOUR_API_TOKEN] --addchatid [YOUR_CHANNEL_NAME]

dove va inserito? grazie

**Comment by mangoppola** [comment]
Quella riga va inserita in una finestra di terminale (prompt dei comandi se usi windows), assicurandoti di essere nella cartella che contiene il file _subito-seacher.py_. Ovviamente, dovrai sostituire il nome canale e il token con i valori opportuni.

**Comment by eliafirenze** [comment]
mi dice: "pyhton3" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

**Comment by eliafirenze** [comment]
C:\Users\Elia\Desktop\morrolinux-subito-it-searcher>
[main 2022-05-07T10:12:57.153Z] window#load: attempt to load window (id: 1)
[main 2022-05-07T10:12:57.225Z] update#setState idle
[main 2022-05-07T10:12:57.343Z] ExtensionHostStarterWorker created
[main 2022-05-07T10:12:58.594Z] window#load: window reported ready (id: 1)
[main 2022-05-07T10:12:58.878Z] Starting extension host with pid 1820 (fork() took 21 ms).
[main 2022-05-07T10:12:58.921Z] ExtensionHostStarterWorker.start() took 69 ms.
[main 2022-05-07T10:13:27.297Z] update#setState checking for updates
[main 2022-05-07T10:13:27.420Z] update#setState idle
[main 2022-05-07T10:14:41.145Z] Extension host with pid 1820 exited with code: 0, signal: null.

poi dopo mi si apre visual studio, che dovrei fare?

**Comment by eliafirenze** [comment]
mi apre Visual Studio e si ferma, scusa potresti magari dare più indicazioni per chi come me è inesperto?
