### ISSUE TITLE
Errore su alcune query con parametri complessi

### ISSUE THREAD

**Issue by guerrieroriccardo** [morrolinux/subito-it-searcher#16]
Salve,
Ho usato il bot per circa un mese senza alcun tipo di problema, ma da circa 2 settimane quando provo a lanciarlo mi si presenta questo errore:
`Adding result: Memoria corsair ddr4 16gb 2x8gb pc3600 vengeance r - 50 € - Ivrea (TO)
Traceback (most recent call last):
  File "\\DC.PRCONSULTING.local\UserProfiles$\riccardo.guerriero\Desktop\subito-it-searcher-master\subito-searcher.py", line 193, in <module>
    run_query(args.url, args.name, False)
  File "\\DC.PRCONSULTING.local\UserProfiles$\riccardo.guerriero\Desktop\subito-it-searcher-master\subito-searcher.py", line 132, in run_query
    location = product.find('span',re.compile(r'town')).string + product.find('span',re.compile(r'city')).string
AttributeError: 'NoneType' object has no attribute 'string'`

Il tutto avviene anche se provo ad aggiungere una nuova query.

**Comment by mangoppola** [comment]
È un problema relativo agli oggetti che sono stati venduti con TuttoSubito ma che non vengono rimossi dal sito. Ho creato una soluzione abbastanza provvisoria a questo problema che _dovrebbe_ funzionare (#17). Purtroppo non ho ancora avuto modo di testarla perchè in realtà il bot non lo sto usando più. Spero ti sia di aiuto.
