### ISSUE TITLE
Codice sorgente cambiato

### ISSUE THREAD

**Issue by marcoscale98** [morrolinux/subito-it-searcher#5]
Credo che il codice sorgente della pagina sia cambiato, mi esce fuori questo errore:
`
Traceback (most recent call last):
  File "subito-searcher.py", line 135, in <module>
    run_query(args.url, args.name)
  File "subito-searcher.py", line 94, in run_query
    location = product.find('div', class_='AdElements__ItemDateLocation--container-L2hvbWUv').find('span').contents[0]
AttributeError: 'NoneType' object has no attribute 'find'
"from" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
`

**Comment by sicca95** [comment]
Sì, ti conviene includere la ricerca con regex per avere una ricerca più inclusiva
